---
baseURL: https://mystifying-mahavira-edbcc1.netlify.com/
footnoteReturnLinkContents: "↩"
theme: gohugo-theme-ananke
MetaDataFormat: yaml
DefaultContentLanguage: en
SectionPagesMenu: main
enableRobotsTXT: true
title: Digital Forest
params:
  background_color_class: bg-white
  custom_css:
  - css/custom.css
  custom_js:
  - js/01_siema.min.js
  - js/02_custom.js
  description: The future is here.
  facebook: "#"
  featured_image: "/images/theorem_hero.png"
  recent_posts_number: 3
  subtitle: Digital Forest rules!
  twitter: https://twitter.com/citrusbyte
permalinks:
  post: "/:year/:month/:title/"
